### ISSUE TITLE
Installation on M3 mac under Sonoma

### ISSUE THREAD

**Issue by CaptainCredible** [andrewreeman/SpectralSuite#59]
Is this possible? How should it be done? can't find any info on this.

**Comment by andrewreeman** [comment]
I do mean to update the README document regarding this but I haven't had time.
I'm also running Sonoma but on intel. You should be able to just run the `.pkg` installer from the release page:
https://github.com/andrewreeman/SpectralSuite/releases/tag/v2.1.10

If you get warnings about security related issues, this is because I'm not a verified publisher as I believe I'd have to pay for a developer account. In this case you will have to allow the pkg installer in your security settings like this: https://support.apple.com/en-gb/guide/mac-help/mh40616/mac

If you run the installer and get another issue just let me know.

Cheers

**Comment by CaptainCredible** [comment]
The installer runs fine, but neither Ableton live or metaplugin recognize
it as a valid vst. no error message.

**Comment by andrewreeman** [comment]
This is strange. I've just tried in Ableton Live now and it seems to show up ok on this laptop. 
I have 'Use VST3 Plug-In System Folders' set to On. 
And the VST3 plugins are installed in `/Library/Audio/Plug-Ins/VST3/SpectralSuite`

I wonder if it is because the plugin is build for intel only, although I'd expect the M series macs to translate that through rosetta.
Here's a build of Bin Scrambler but apparently for intel and arm:
https://github.com/andrewreeman/SpectralSuite/blob/8e69816be31d71f13a1b117653f425b9735f2222/Bin%20Scrambler.vst3.zip

Let me know you experience using that, if it works I'll try and do a build for both architectures

<img width="1068" alt="Screenshot 2024-06-24 at 22 13 29" src="https://github.com/andrewreeman/SpectralSuite/assets/1423405/fea2825e-78b2-4aaa-b1cd-80e63c03208a">

**Comment by CaptainCredible** [comment]
Yes! tThat worked under Ableton Live 12 on Sonoma using an M3! a build for
both architectures would be great.

**Comment by CaptainCredible** [comment]
No, wait, sorry, jumped the gun on that one. The GUI loads up but the audio
output is just the unprocessed dry input.

The Audio Units versions work in other software but not in Live

**Comment by CaptainCredible** [comment]
Ok, sorry I am new to Mac, the solution was installing rosetta via terminal
and setting Ableton to run in rosetta mode (CMD + I for the settings). then
everything works.
[image: image.png]

**Comment by andrewreeman** [comment]
That's great to hear. Hopefully your existing plugins work ok too in rosetta mode.
It's strange that multi-architecture build did not work. 

I will close this issue but feel free to add comments or open a new issue if you experience problems.

Thanks!

**Comment by CaptainCredible** [comment]
Yes the existing plugins work in rosetta
